name: test
on:
  push:
    branches:
      - 'master'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: npm install --global npm@8
      - name: Run test
        run: npx jest
